presubmits:
  - name: nmath-unit-test
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:2
        command:
        - make
        args:
        - unit

  - name: nmath-lint
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:2
        command:
        - make
        args:
        - lint

  - name: nmath-test-gosec
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:2
        command:
        - make
        args:
        - gosec
        
  - name: nmath-test-license-header
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers: ghcr.io/google/addlicense:v1.1.1
      - image: 
        command:
        - addlicense
        args:
        - "-c"
        - "."

postsubmits:
  - name: build-push-image
    cluster: default
    run_if_changed: "^VERSION$"
    branches:
    - main
    - master
    annotations:
      description: Build and Push Image to DockerHub
    decorate: true
    decoration_config:
      censor_secrets: true
    max_concurrency: 1
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:debug
        command:
        - "/bin/sh"
        - "-c"
        - |
          executor --context=${PWD} \
            --dockerfile=Dockerfile --destination=nephio/nmath:${BUILD_ID}
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker/
        resources:
          requests:
            cpu: 2
            memory: 2Gi
      volumes:
        - name: kaniko-secret
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json
